- 搜索引擎:
    trunall: off
    engine:
      - bing: "https://www.bing.com/search?q="
      - 谷歌: "https://www.google.com/search?q="
      - 百度: ""
- 网盘全搜索on:
    trunall: on
    engine:
      - yiso: "https://yiso.fun/info?searchKey="
      - 混合盘: "https://hunhepan.com/search?q="
- 单个网盘:
    trunall: off
    engine:
      - yiso: "https://yiso.fun/info?searchKey="
      - 混合盘: "https://hunhepan.com/search?q="